server:
  port: 8003

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: replica2
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://replica1:8002/eureka/
  server:
    enable-self-preservation: false
